### ISSUE TITLE
Unable to construct a valid mutation

### ISSUE THREAD

**Issue by alex-r89** [CamiloGarciaLaRotta/watermelon-http-client#157]
Hi there,

Sorry for another question!

Im struggling to work out how to construct a valid mutation in the yml file. I have managed to hit my resolver using cURL and using Postman, but am unable to work out the correct structure in the YML.

The error my Action is getting is:
```js
response status: 500
response body: "POST body missing. Did you forget use body-parser middleware?"
```

My yml is as follows, which afaik is basically exactly the same as the example mutation:

```yml
name: Create New Event
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  test:
    name: Create Auction Action
    runs-on: ubuntu-latest
    steps:
      - name: Create the event
        id: mutation
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          headers: '{"Authorization": "bearer ${{ secrets.AUTH_HEADER_STRING }}", "Origin": "https://github.net" }'
          url: 'https://api.myDomain.net'
          graphql: |
            mutation CreateEvent {
              createEvent {
                message
                success
                }
              }
            }
```

I can see the request hitting my server, so I know this part is fine, but there is something wrong with the format of the mutation. The body-parser middleware isnt required in apollo server 2.x so I know its not related to this either.

The mutation has no input variables, so I thought this would be pretty straight forward.

Any advice at all on this one?

Thanks!
