### ISSUE TITLE
Support custom headers

### ISSUE THREAD

**Issue by fabasoad** [CamiloGarciaLaRotta/watermelon-http-client#4]
Would be great to support custom headers (so I can use this action in my project 😄 ).

**Comment by CamiloGarciaLaRotta** [comment]
happy to get that working! PRs are also welcome 🙌🏽

I was thinking of a key-valye format. Would this work for you @fabasoad ? 🤔

```yml
uses: CamiloGarciaLaRotta/watermelon-http-client@v1
with:
  url: <some-url>
  method: post
  data: <some-data>
  headers:
    Accept: "audio/*; q=0.2, audio/basic"
    Cache-Control: no-cache
    Foo-Header: "!*$#"
    
```

**Comment by CamiloGarciaLaRotta** [comment]
This would also address https://github.com/CamiloGarciaLaRotta/watermelon-http-client/issues/3

**Comment by CamiloGarciaLaRotta** [comment]
huh apparently hash/array inputs are currently [not supported](https://github.community/t5/GitHub-Actions/Can-action-inputs-be-arrays/m-p/33804), but we can use the following workaround:

```yml
uses: CamiloGarciaLaRotta/watermelon-http-client@v1
with:
  url: <some-url>
  method: post
  data: <some-data>
  headers: |
    {
      'Accept': ' "audio/*; q=0.2, audio/basic" ',
      'Cache-Control': 'no-cache',
      'Foo-Header': '!*$#'
    }
```
